### ISSUE TITLE
File force close on windows 10

### ISSUE THREAD

**Issue by MrBoss254** [Glacier-Labs/node-bootstrap#2]
The file tries to open and then force closes itself. Repeats every time you click 'open file' any fix to that?

**Comment by Bart200c** [comment]
> The file tries to open and then force closes itself. Repeats every time you click 'open file' any fix to that?

Please try executing the [verifier_windows_amd64.exe](https://github.com/Glacier-Labs/node-bootstrap/releases/download/v0.0.2-beta/verifier_windows_amd64.exe) in PowerShell, and ensure it is configured correctly.
